env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/essential
  - standard
  - ./.eslintrc-auto-import.json
parserOptions:
  ecmaVersion: 14
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  'vue/multi-word-component-names': 0
}
