env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/essential
  - standard
parserOptions:
  ecmaVersion: 14
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
